### ISSUE TITLE
Remove the if statement from the `ddev get drud/ddev-beanstalkd` output

### ISSUE THREAD

**Issue by rpkoller** [ddev/ddev-beanstalkd#1]
If you install the beanstalkd add-on you get currently the following output with ddev 1.19.0: 
```
$> ddev get drud/ddev-beanstalkd
Downloading https://api.github.com/repos/drud/ddev-beanstalkd/tarball/v1.1.2
v1.1.2_3835960589.tar.gz 6.29 KiB / ? [------------------------------------------------------------------=------------------------------------------------------------------------------------------------------------]  64.45% 0s
if [ "$(arch)" = "arm64" -o "$(arch)" = "aarch64" ]; then echo "This package does not work on arm64 machines"; exit 1; fi

Installed file /Users/myuser/Sites/happen/.ddev/docker-compose.beanstalkd.yaml
Downloaded add-on drud/ddev-beanstalkd, use `ddev restart` to enable.
For more information about this add-on visit the source repo at
https://github.com/drud/ddev-beanstalkd
Please file issues and create pull requests there to improve it.
```
The string `if [ "$(arch)" = "arm64" -o "$(arch)" = "aarch64" ]; then echo "This package does not work on arm64 machines"; exit 1; fi` might be hidden from the users. it doesn`t provide any benefit or information and is rather confusing for the user.

**Comment by rfay** [comment]
This is actually output from the pre-install action, and I think it belongs there, but with better explanation of what's going on.

Output will be improved by 
* https://github.com/drud/ddev/pull/3711
